# Generated by Django 5.2 on 2025-05-29 03:51

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(
                    location="/Users/mohantejadharmavarapu/Projects/EventHub/backend/media/profile_pictures"
                ),
                upload_to="",
                verbose_name="profile_image",
            ),
        ),
    ]
