# Generated by Django 6.0.2 on 2026-02-10 11:11

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/Users/mohantejadharmavarapu/Projects/eventhub/backend/media/profile_pictures'), upload_to='', verbose_name='profile_image'),
        ),
    ]
